### ISSUE TITLE
Filter by multiple phone numbers (without getting full call Log in a loop)

### ISSUE THREAD

**Issue by ChristopherBull** [creacore-team/cordova-plugin-calllog#1]
Hi,

This is a feature request.

I am in need of filtering the call log for a list/series of phone numbers. As far as I can tell from your documentation, I have to call getCallLog() with updated filters for each separate phone number.

A common use case may be searching for a phone number starting with a '0', but also searching for the same number with the country code (e.g. '+44').

I currently workaround this by calling getCallLog() in a loop, but would prefer it to be more efficient if possible.

Thanks for the plugin.

**Comment by Bruno361** [comment]
Hi,
That would be an interesting feature, indeed.
We will soon implement a 'like' operator (to allow searching for phone numbers starting with '+44') and make possible the use of an array of values with the == operator

**Comment by VoltX** [comment]
@CaffeinatedAndroid 
Feature added in 1.2.0 (55b988bdf0b786c723ee07dc09fb61273329d82c), enjoy

**Comment by ChristopherBull** [comment]
Super :+1:
