### ISSUE TITLE
can we detect a incoming call?

### ISSUE THREAD

**Issue by aohan237** [creacore-team/cordova-plugin-calllog#12]
can we detect a incoming call?

**Comment by Bruno361** [comment]
You cannot do that with this plugin, the goal of this plugin is to retrieve the call logs.

**Comment by aohan237** [comment]
thanks.
can you help me about, how can we detect an incoming call ,is there any cordova plugin can do this?

**Comment by VoltX** [comment]
Sure
https://www.npmjs.com/package/tcg.plugin.phonecalltrap

**Comment by aohan237** [comment]
@VoltX  thanks a lot
