### ISSUE TITLE
Additional filters do not apply when filtering a list of numbers

### ISSUE THREAD

**Issue by ChristopherBull** [creacore-team/cordova-plugin-calllog#2]
I am no longer able to use additional filters when searching for a list of numbers.

When I search for a single number, specifying "value" as a String, all of the filters apply. If I search for a list of numbers, i.e. an array of String phone numbers, the callback returns all instances of the specified numbers.

For clarity:
It always gets correct phone numbers (either searching for a specific one or a list), but when I search for a list of numbers and filter for outgoing type and made within the last month, the list search appears to ignore/skip filtering by type and date.

This issue is related to the update for filtering by list/array of phone numbers enhancement: #1 
The 'date' and 'type' filters worked on single numbers before version 1.2.1

My code:

```JS
var d = new Date();
d.setMonth(d.getMonth() - 1); // Timestamp 1 month ago

var filters = [
    {
        'name': 'number',
        'value': ['01234567890', '01234987654', '01234101010'], // Fake (representative) data, of course. Use real numbers
        'operator': '==',
    },
    {
        'name': 'date',
        'value': d.getTime(),
        'operator': '>='
    },
    {
        'name': 'type',
        // https://developer.android.com/reference/android/provider/CallLog.Calls.html
        'value': 2, // Outgoing call
        'operator': '==',
    },
];

// Get filtered call log
window.plugins.callLog.getCallLog(filters,
    fnGetCallLogSuccess,
    fnGetCallLogFail);
```

**Comment by Bruno361** [comment]
Hi,
Yes, the correction required by the multiple values was in the dev branch, which we have just merged.
Can you confirm that it is now ok for your use case ?

**Comment by ChristopherBull** [comment]
I can confirm it now works as expected in v1.2.2
Thanks a bunch.
