### ISSUE TITLE
typescript error when compiling filters

### ISSUE THREAD

**Issue by justinmccombs** [creacore-team/cordova-plugin-calllog#4]
My filters are set as:

` 
let filters = [  
                    {  
                        "name": "date",  
                        "operator": ">=",  
                        "value": queryDate.unix()  
                    },  
                    {  
                        "name": "duration",  
                        "operator": ">",  
                        "value": "2"  
                    }  
                ]  
`

where queryDate.unix() returns a timestamp.  When testing in browser, this all works great.  However, when I go to compile to android, I get the following error:

Argument of type '{ "name": string; "operator": string; "value": any; }[]' is not assignable to parameter of  type 'CallLogObject[]'. Type '{ "name": string; "operator": string; "value": any; }' is not assignable to type 'CallLogObject'. Types of property 'operator' are incompatible. Type 'string' is not assignable to type
            '"==" | "!=" | ">" | ">=" | "<" | "<=" | "like"'.

     L129:                  this.callLog.getCallLog(filters).then( (logs) => {
     L130:                      if(logs.length) {

**Comment by Bruno361** [comment]
Try using `<CallLogObject>` to force the type of parameters you are using for the Typescript compiler:

`let filters: CallLogObject[] = [ <CallLogObject>{ "name": "date", "operator": ">=", "value": queryDate.unix() }, <CallLogObject>{ "name": "duration", "operator": ">", "value": "2" } ]`
