### ISSUE TITLE
window.plugins.callLog Cannot read property 'callLog' of undefined

### ISSUE THREAD

**Issue by mawais78** [creacore-team/cordova-plugin-calllog#5]
I just installed plugin and now I'm try to use this in deviceready function. All other functions are working but this is not.

Here is my code inside of deviceready function

```
        let filters = [{
            "name": "date",
            "value": 1517266800000,
            "operator": ">="
        }];

        window.plugins.callLog.getCallLog(filters, function(data) {
            $('.recent-calls').text(JSON.stringify(data));
            console.log(data);
        }, function() {
        });
```

**Comment by Bruno361** [comment]
It seems your `window.plugins` is not defined, which is an error that occurs _before_ our plugin is involved.

Can you check the environment in which you are running this code and ensure that the plugins are available ?

**Comment by mawais78** [comment]
Thank you for quick response. I don't know how to define window.plugins Can you please tell me this?

I'm running this in windows 10, cordova 8.0.0
Yes I made sure plugin is installed successfully.

I also removed platform and then added again and then I created a new build. but it is not working.

**Comment by Bruno361** [comment]
It does seem to be related to your cordova setup. Are other plugins working ?
Try uninstalling and reinstalling the plugin and rebuilding the project entirely. 

If it doesn't work, are you using pure Cordova, or accessing the plugin through a framework such as Ionic ?

**Comment by mawais78** [comment]
Yes other plugins are working fine.

I tried uninstalling and installing plugin thrice. and I removed and added again android platform

Yes I'm suing pure cordova.

**Comment by Bruno361** [comment]
Can you provide more of your code, then ?

**Comment by mawais78** [comment]
I've uploading my full project so you can reproduce issue on your side.

here is ths link of the project https://goo.gl/2Lbomk

**Comment by Bruno361** [comment]
Thx, I will try to test it myself when I find some time.

Can you also confirm that you are testing on an Android device, and not in the browser ?

**Comment by mawais78** [comment]
Thank you. I'm testing on browser and on galaxy S8+

**Comment by Bruno361** [comment]
There are two issues:

- you should not test in the browser, because window.plugins is not defined there, and this plugin is Android only

- in your code, you are missing a `window.plugins.callLog.requestReadPermission();` to request the necessary permissions from Android. Without it, you will not be able to use the plugin.

**Comment by mawais78** [comment]
Thank you so much you saved my life. This is working.
