### ISSUE TITLE
Not getting any output

### ISSUE THREAD

**Issue by acedigibits** [creacore-team/cordova-plugin-calllog#6]
I have put read permission and am getting console for read and 'get_data'  but no error or console for window.plugins.callLog.getCallLog. Below is the code i used. I even tried filter with numbers but no console.log of data or error.

 $scope.get_calls_permissions = function() {
            if (device.platform == 'Android') {
                if (!$scope.hasReadPermission) {
                    window.plugins.callLog.hasReadPermission(function() {
                        console.log('get_read_permission');
                        $scope.hasReadPermission = true;
                        $scope.get_calls();

                    }, function() {
                        console.log('error get_read_permission');
                        window.plugins.callLog.requestReadPermission(function() {
                            console.log('get_request_permission');
                            $scope.hasReadPermission = true;
                            $scope.get_calls();
                        }, function() {
                            alert('Insert App Exit');
                            return;
                        })
                    })

                    return;
                } else {
                    $scope.get_calls();
                }

            } else {
                alert('Platform not supported');
            }
        }
        $scope.get_calls = function() {
            console.log('get_data');
            let filters = [{
                "name": "date",
                "value": 1517266800000,
                "operator": ">="
            }];
            window.plugins.callLog.getCallLog(filters, function(data) {
                console.log('data_fetched');
                console.log(data);
            }, function(error) {
                console.log(error);
                // Error
            });
        }

**Comment by Bruno361** [comment]
Hi,
I am very sorry but we don't have enough time to give user support right now. If you feel there is an actual issue with the plugin, please provide more detailed information about the exact conditions of the issue.

**Comment by viamage** [comment]
You could leave the issue open, maybe community would help if you're not willing to. 

I'm running into very similar problem in my cordova-vue app. It goes through permission request, triggers success callback on it, but then in

```
console.log('LOADING CALLS')
let filters = []
window.plugins.callLog.getCallLog(filters, function (data) {
          console.log('CALLS: ', data)
          this.calls = data;
        }, function (err) {
          console.log('CALLS ERR', err)
        })
```
nothing happens. 

```
(...)
2018-12-08 16:32:30.505 8594-8594/com.viamage.a4calls I/chromium: [INFO:CONSOLE(1)] "LOADING CALLS", source: file:///android_asset/www/static/js/app.277bab910e0606823012.js (1)

// that's it, nothing more from the app. 
```


@acedigibits were you able to resolve it on your own?
