### ISSUE TITLE
Issue with Date and Photo URI

### ISSUE THREAD

**Issue by arjunmenon** [creacore-team/cordova-plugin-calllog#7]
Hey
The timestamp returned is something like `1538642294468` which turns out to be `Sat, 20 Aug 50727 21:21:08 GMT`

Because of which, it is also hard to tell how the returned object is sorted? Is it recent calls to old calls?

Also, there is no photo_uri returned for the contact?

I am using the code documented in the Readme, tested in Phonegap Android 7.

```javascript

cachedName: "<Contact Name>"
cachedNumberLabel: 0
cachedNumberType: 2
contact: ""
date: 1538642294468
duration: 14
name: "<Contact Name>"
new: 0
number: "<Contact Number>"
phoneAccountId: "1"
photo: ""
thumbPhoto: ""
type: 2
viaNumber: ""
```
The date is strange; There is no photo uri even though I have set a photo.

**Comment by VoltX** [comment]
Hi, the time is in milliseconds, just divide it by 1000

The photo_uri is returned only if found. Maybe not returned because there is not picture associated with the contact ? Maybe all permissions are not granted ?

**Comment by arjunmenon** [comment]
For permissions, I am simply doing
```javascript
window.plugins.callLog.requestReadPermission(function(success) {console.error(success);}, function(error) {console.error(error);});
> VM125:1 OK

window.plugins.callLog.hasReadPermission(function(success) {console.error(success);}, function(error) {console.error(error);});
> VM131:1 true
```

But it still does not return the photo uri. I have also manually turned on the storage permissions as well. But still nothing. The contact has photo set to them. But the object returned does not show the uri.

**Comment by Bruno361** [comment]
Hi,
I am very sorry but we don't have enough time to give user support right now. The photo URIs are returned correctly in our internal tests. If you feel there is an actual issue with the plugin, please provide more detailed information about the exact conditions of the issue.
