### ISSUE TITLE
getting Just Top 500 numbers

### ISSUE THREAD

**Issue by adelsadek1** [creacore-team/cordova-plugin-calllog#8]
Hello,
I am trying to fetch my log But Unfortunately I got Just top 500 logs.
and Here Is My Filter 
this.num = [{
      "name": "date",
      "value": 1514821592,
      "operator": ">=",
  }];
   this.callLog.getCallLog(this.num).then(res => {
      this.mobileNumbers = res;
    })
  }
Thanks

**Comment by Bruno361** [comment]
Hi,
That's because some Android phones have a limited number of calls logged. There is nothing we can do about it with this plugin.

**Comment by adelsadek1** [comment]
ok, Thanks
