### ISSUE TITLE
Plugin Does Not Work!

### ISSUE THREAD

**Issue by adelsadek1** [creacore-team/cordova-plugin-calllog#9]
Hello
Is There Any Reason For This Plugin Work In Some Devices And Stop Others
I have tried this plugin on a device but it doesn't work so if there any requirements for this plugin, please Show me.
 here The Device Information which I tried on it
**Device Name** => Redmi5
**Android Version** => 7.1.2   N2G47H

Thanks

**Comment by VoltX** [comment]
Hello,
This plugin works for most people.

Could you provide more details about things that don't work ? Compilation error, console error, error in results, ... ?

Returned values can be different according to versions as described at the end of README.

Thanks

**Comment by adelsadek1** [comment]
Hi VoltX,
I am not talking about the different returned value it does not give me any result I have asked you about if there any requirements and minimum android version.
Thanks

**Comment by VoltX** [comment]
No requirements, no minimum version.

**Comment by adelsadek1** [comment]
Thanks
I will try again

**Comment by VoltX** [comment]
There are no specifics requirements. Minimum android version is the same as cordova (API 14 = android 4.0)

If you don't get any results, maybe your authorisation request failed (READ_CALL_LOG and READ_CONTACTS). Check with hasReadPermission().

Please follow the procedure explained in the README and provide precise information if you have issues.

**Comment by mobileDev2020** [comment]
Hi, 
Does this plugin still work after Google Play added new restrictions on requesting user permissions for Call Logs from app?
 I am referring to this - 

[https://support.google.com/googleplay/android-developer/answer/9047303]

Thanks!

**Comment by Bruno361** [comment]
Hi, the plugin cannot be used for general statistics apps anymore, but it will still perfectly work for the Permitted uses listed in the link you mentioned.

**Comment by mobileDev2020** [comment]
Hi,
Are there any alternate cordova plugins that can be used to update/delete call logs without getting flagged by Google Play ?

Thanks

**Comment by Bruno361** [comment]
I think that this Google Play policy applies in similar way to all plugins and apps ;)
